/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Programm;

import Klassen.Buchungsliste;
import Klassen.Gast;
import Klassen.GastExceptions;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author famz
 */
public class programm extends javax.swing.JFrame {

    /**
     * Creates new form programm
     */
    public programm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAngefragt = new javax.swing.JList<>();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldBett = new javax.swing.JTextField();
        jToggleButtonAdd = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaBestaetigt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldBettBestaetigt = new javax.swing.JTextField();
        jButtonBestaetigt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonUnbestaetigt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDatei = new javax.swing.JMenu();
        jMenuItemDatei1 = new javax.swing.JMenuItem();
        jMenuItemDatei2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDatei3 = new javax.swing.JMenuItem();
        jMenuBearbeiten = new javax.swing.JMenu();
        jMenuItemBearbeiten1 = new javax.swing.JMenuItem();
        jMenuItemBearbeiten2 = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jMenuItemAbout1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buchungen für Fulda");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setText("Buchungsliste");

        jListAngefragt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAngefragtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListAngefragt);

        jToggleButtonAdd.setText("Hinzufügen");
        jToggleButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAddActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Anzahl Betten");

        jLabel4.setText("Angefragt");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextAreaBestaetigt.setColumns(20);
        jTextAreaBestaetigt.setRows(5);
        jScrollPane2.setViewportView(jTextAreaBestaetigt);

        jLabel5.setText("Bestätigt");

        jButtonBestaetigt.setText("-->");
        jButtonBestaetigt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBestaetigtActionPerformed(evt);
            }
        });

        jLabel6.setText("kommen mit");

        jLabel8.setText("Personen");

        jButtonUnbestaetigt.setText("<--");
        jButtonUnbestaetigt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnbestaetigtActionPerformed(evt);
            }
        });

        jMenuDatei.setText("Datei");

        jMenuItemDatei1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDatei1.setText("Neu");
        jMenuDatei.add(jMenuItemDatei1);

        jMenuItemDatei2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDatei2.setText("Öffnen");
        jMenuDatei.add(jMenuItemDatei2);
        jMenuDatei.add(jSeparator1);

        jMenuItemDatei3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemDatei3.setText("Beenden");
        jMenuDatei.add(jMenuItemDatei3);

        jMenuBar1.add(jMenuDatei);

        jMenuBearbeiten.setText("Bearbeiten");

        jMenuItemBearbeiten1.setText("Markierten Gast löschen");
        jMenuItemBearbeiten1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBearbeiten1ActionPerformed(evt);
            }
        });
        jMenuBearbeiten.add(jMenuItemBearbeiten1);

        jMenuItemBearbeiten2.setText("jMenuItem1");
        jMenuBearbeiten.add(jMenuItemBearbeiten2);

        jMenuBar1.add(jMenuBearbeiten);

        jMenuAbout.setText("Über");

        jMenuItemAbout1.setText("Über Buchungsliste");
        jMenuAbout.add(jMenuItemAbout1);

        jMenuBar1.add(jMenuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldBettBestaetigt)
                                    .addComponent(jButtonBestaetigt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jButtonUnbestaetigt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldBett, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButtonAdd))
                    .addComponent(jLabel3))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBett, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldBettBestaetigt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBestaetigt)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonUnbestaetigt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAddActionPerformed
        try {
            String name = jTextFieldName.getText();
            int bett = Integer.valueOf(jTextFieldBett.getText());
            buchungsliste.add(new Gast(name, bett));
            aktuallisiereAnzeige();
        } catch (GastExceptions ex) {
            Logger.getLogger(programm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jToggleButtonAddActionPerformed

    private void jButtonBestaetigtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBestaetigtActionPerformed
        try {
            int a = jListAngefragt.getSelectedIndex();
            String name = buchungsliste.get(a).getName();
            int bett = Integer.valueOf(jTextFieldBettBestaetigt.getText());
            zugesagt.add(new Gast(name, bett));
            buchungsliste.remove(a);
            aktuallisiereAnzeige();
        } catch (GastExceptions ex) {
            Logger.getLogger(programm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonBestaetigtActionPerformed

    private void jListAngefragtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAngefragtMouseClicked
        //Bei Auswahl eines Eintrags aus der Liste wird die bestätigte Bettenanzahl mit der angefragten vorbelegt
        int select = jListAngefragt.getSelectedIndex();
        jTextFieldBettBestaetigt.setText(String.valueOf(buchungsliste.get(select).getBett()));
    }//GEN-LAST:event_jListAngefragtMouseClicked

    private void jMenuItemBearbeiten1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBearbeiten1ActionPerformed
        if (jListAngefragt.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(rootPane, "Bitte einen angefragten Gast zum löschen auswählen.");
        } else {
            int loeschen = jListAngefragt.getSelectedIndex();
            String name = buchungsliste.get(loeschen).getName();

            int eingabe = JOptionPane.showConfirmDialog(rootPane, "Soll der Gast " + name + " wirklich gelöscht werden?", "Bestätigungsanfrage", JOptionPane.YES_NO_OPTION);
            if (eingabe == 0) {
                buchungsliste.remove(loeschen);
                aktuallisiereAnzeige();
            }

            
        }
    }//GEN-LAST:event_jMenuItemBearbeiten1ActionPerformed

    private void jButtonUnbestaetigtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnbestaetigtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUnbestaetigtActionPerformed
    public void aktuallisiereAnzeige() {
        jTextFieldName.setText("");
        jTextFieldBett.setText("");
        jTextFieldBettBestaetigt.setText("");
        DefaultComboBoxModel model = new DefaultComboBoxModel(buchungsliste.toArray());
        jListAngefragt.setModel(model);
        jTextAreaBestaetigt.setText(zugesagt.toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(programm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(programm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(programm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(programm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new programm().setVisible(true);

            }
        });
    }
    Buchungsliste buchungsliste = new Buchungsliste();
    Buchungsliste zugesagt = new Buchungsliste();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBestaetigt;
    private javax.swing.JButton jButtonUnbestaetigt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListAngefragt;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBearbeiten;
    private javax.swing.JMenu jMenuDatei;
    private javax.swing.JMenuItem jMenuItemAbout1;
    private javax.swing.JMenuItem jMenuItemBearbeiten1;
    private javax.swing.JMenuItem jMenuItemBearbeiten2;
    private javax.swing.JMenuItem jMenuItemDatei1;
    private javax.swing.JMenuItem jMenuItemDatei2;
    private javax.swing.JMenuItem jMenuItemDatei3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextAreaBestaetigt;
    private javax.swing.JTextField jTextFieldBett;
    private javax.swing.JTextField jTextFieldBettBestaetigt;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JToggleButton jToggleButtonAdd;
    // End of variables declaration//GEN-END:variables
}
